[google_service_account]
service_account_json = """{
  "type": "service_account",
  "project_id": "adept-rock-445911-p3",
  "private_key_id": "6f1266b2435a3b29d44641d3b5f3580128bd13c6",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkq...\n-----END PRIVATE KEY-----\n",
  "client_email": "employee-tracking-system@adept-rock-445911-p3.iam.gserviceaccount.com",
  "client_id": "104748634869645216072",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/employee-tracking-system%40adept-rock-445911-p3.iam.gserviceaccount.com"
}"""
